# Taps
tap 'homebrew/cask'
tap 'homebrew/cask-eid'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils' # Those that come with macOS are outdated
brew 'go'
brew 'imagemagick'
brew 'openssl'
brew 'unrar'
brew 'youtube-dl'
brew 'hugo'

cask 'handbrake'
cask 'transmission'
cask 'vlc'
cask 'ngrok'
cask 'iterm2'

cask 'slack'
cask 'google-chrome'
cask 'alfred'
cask 'bartender'
cask 'fork'
cask 'camtasia'
cask 'amazon-music'
cask 'google-drive-file-stream'
cask 'caffeine'
cask 'clipgrab'
cask '1password'
cask 'the-unarchiver'
cask 'spectacle'
cask 'visual-studio-code'

cask 'muzzle'
cask 'rocket'
cask 'twist'
cask 'scroll-reverser'
cask 'switchresx'
